Methods and fields
ollykel/v-vim pull request #4
Opened 2019-07-09 22:26 UTC by ernierasta

Add option to highlight methods (function calls) and/or object fields, so:

```go
// free highlighted:
req.free('test')

// headers highlighted:
req.headers
```
It is rip off from [vim-go](https://github.com/fatih/vim-go/blob/master/syntax/go.vim).

Added configuration for it and documentation in README.md for all current options.

2019-07-10 20:25 UTC, ollykel requested changes
Good job on this one! It'll make a great addition to the codebase.

I requested a few minor changes (see the comments), but it's just about good to go.

2019-07-10 20:25 UTC, ollykel commented on syntax/vlang.vim
> +  syn match vFunctionCall      /\w\+\ze(/ contains=goBuiltins,goDeclaration
Just change goBuiltins and goDeclaration to vBuiltins and vDeclaration here.

2019-07-10 20:25 UTC, ollykel commented on README.md
> +```vim
Good catch, thank you!

2019-07-10 20:25 UTC, ollykel commented on syntax/vlang.vim
> +if !exists('g:v_highlight_functions_calls')
Typo here: should be 'g:v_highlight_function_calls'

2019-07-10 20:25 UTC, ollykel commented on syntax/vlang.vim
> +hi def link     vFunctionCall      Type
Just a personal preference: could you change "Type" to "Special"?  I'm trying to reserve Type highlighting for types only. I'm going to change json.encode and json.decode to vBuiltins for the same reason.

2019-07-11 10:56 UTC, ernierasta commented on syntax/vlang.vim
> +  syn match vFunctionCall      /\w\+\ze(/ contains=goBuiltins,goDeclaration
I am blind ... thank you!

2019-07-11 10:57 UTC, ernierasta commented on README.md
> +```vim
my own typo :-)

2019-07-11 10:59 UTC, ernierasta commented on syntax/vlang.vim
> +if !exists('g:v_highlight_functions_calls')
done, thank you

2019-07-11 22:27 UTC, ollykel approved these changes
Great job, thanks again!

2019-07-11 22:28 UTC, merged